[platformio]
default_envs = iv6_v2

[env]
platform = espressif8266
framework = arduino
board = esp8285
monitor_speed = 115200
upload_resetmethod = nodemcu
upload_speed = 115200
board_build.filesystem = littlefs
board_build.ldscript = eagle.flash.1m256.ld
lib_deps =
  bblanchon/ArduinoJson @ ^7.2.0
  makuna/NeoPixelBus @ ^2.7.9
  paulstoffregen/Time @ ^1.6.1
  jchristensen/Timezone @ ^1.2.4
  khoih-prog/ESP8266TimerInterrupt @ ^1.6.0
build_flags =
  -D FW_VERSION=\"6.0.0\"
  -Wall

[env:iv6]
build_flags =
  ${env.build_flags}
  -DCLOCK_VERSION_IV6

[env:iv6_v2]
build_flags =
  ${env.build_flags}
  -DCLOCK_VERSION_IV6_V2

[env:iv12]
build_flags =
  ${env.build_flags}
  -DCLOCK_VERSION_IV12

[env:iv22]
build_flags =
  ${env.build_flags}
  -DCLOCK_VERSION_IV22
